INSERT INTO estados (nome, sigla, regiao, populacao)
VALUES 
    ('Bahia', 'BA', 'Nordeste', 14.9),
    ('Ceará', 'CE', 'Nordeste', 9.1),
    ('Distrito Federal', 'DF', 'Centro-Oeste', 3.1),
    ('Espírito Santo', 'ES', 'Sudeste', 4.0),
    ('Goiás', 'GO', 'Centro-Oeste', 7.1),
    ('Maranhão', 'MA', 'Nordeste', 7.1),
    ('Mato Grosso', 'MT', 'Centro-Oeste', 3.5),
    ('Mato Grosso do Sul', 'MS', 'Centro-Oeste', 2.8),
    ('Minas Gerais', 'MG', 'Sudeste', 21.2),
    ('Pará', 'PA', 'Norte', 8.7),
    ('Paraíba', 'PB', 'Nordeste', 4.0),
    ('Paraná', 'PR', 'Sul', 11.6),
    ('Pernambuco', 'PE', 'Nordeste', 9.6),
    ('Piauí', 'PI', 'Nordeste', 3.3),
    ('Rio de Janeiro', 'RJ', 'Sudeste', 17.3),
    ('Rio Grande do Norte', 'RN', 'Nordeste', 3.5),
    ('Rio Grande do Sul', 'RS', 'Sul', 11.4),
    ('Rondônia', 'RO', 'Norte', 1.8),
    ('Roraima', 'RR', 'Norte', 0.63),
    ('Santa Catarina', 'SC', 'Sul', 7.2),
    ('São Paulo', 'SP', 'Sudeste', 45.9),
    ('Sergipe', 'SE', 'Nordeste', 2.3),
    ('Tocantins', 'TO', 'Norte', 1.6);